### PR TITLE
NLP and Data Quality field level insights

### LINKED ISSUE #33: Add NLP data quality  field level insights
This is in support of WHWFFHCDM-287 jira ticket to define model extensions to support field & value level data quality and NLP insights.

### PR DESCRIPTION
**Pull request by kimkenna**
This is in support of WHWFFHCDM-287 jira ticket to define model extensions to support field & value level data quality and NLP insights.

### CODE REVIEW

**Review by dipanjanmukherjeeibm — COMMENTED** [review]
InsightDetailExtensions.fsh

- InsightReference extension has cardinality 1..1, meaning mandatory, is that correct?

InsightExtensions.fsh

- the extension 'path' is very close to FHIR reserved word, maybe use 'insight-path' or similar?similar comment for SourceId and Category

InsightResultExtensions.fsh

- InsightValue extension doesn't seem to have a value[x] binding, is that correct?

**Review by dipanjanmukherjeeibm — COMMENTED** [review]
InsightSpanExtension.fsh

- don't see the definition of InsightConfidence extension at the end

**Review by dipanjanmukherjeeibm — CHANGES_REQUESTED** [review]
Vocabulary / AliasCodingSystems.fsh

- I checked that the alias LOINC for LOINCD codes is incorrect, I think it is missing a .org the correct one should be http://loinc.org

**Comment by kimkenna** [comment]
Thanks for the thorough review @dipanjanmukherjeeibm !  Here's my responses based on your feedback and the guild discussion earlier today:

1. InsightReference extension cardinality modified to 0..1 instead of 1..1;
2. Path, SourceId and Category extension naming will remain the same so can be used by other profiles in future; But, I did modify the base extension description for these to lend them to being for a potentially broader purpose;
3. InsightValue extension is intended to allow "any" data type; This is the only way I found in Sushi to do that (not declare a specific binding); 
4. The definition for InsightConfidence is in it's own InsightConfidenceExtensions.fsh file since this extension is used in more then one profile in the overall model
5. Good catch on the URL for LOINC. Updated to use http://loinc.org instead

**Comment by dipanjanmukherjeeibm** [comment]
@kimkenna , all the changes look good, thanks for the update

**Review by dipanjanmukherjeeibm — APPROVED** [review]

**Pull request merged**
